// App
export const HANDLE_ERROR = 'HANDLE_ERROR';
export const SAVE_IP = 'SAVE_IP';
export const SAVE_MAP_KEY = 'SAVE_MAP_KEY';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_GEO_NAME = 'UPDATE_GEO_NAME';
export const UPDATE_ADDRESS_NAME = 'UPDATE_ADDRESS_NAME';
export const APP_CONTROLL_STATE = 'APP_CONTROLL_STATE';
export const APPUPDATE = 'APPUPDATE';
export const ISLOCATION = 'ISLOCATION';
//JST_Token
export const SAVE_JWT_TOKEN = 'SAVE_JWT_TOKEN';
export const SAVE_ID = 'SAVE_ID';
export const PREORDER_DATE = 'PREORDER_DATE';
export const PREORDER_TIME = 'PREORDER_TIME';
export const SAVE_BRANCH = 'SAVE_BRANCH';

// User
export const SAVE_USER = 'SAVE_USER';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';
export const SAVE_NOTIFYID = 'SAVE_NOTIFYID';
export const UPDATE_SHOP = 'UPDATE_SHOP';
export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_PRE_ORDER = 'UPDATE_PRE_ORDER';
export const SAVE_ADDRESSES = 'SAVE_ADDRESSES';
export const UPDATE_SELECTED_ADDRESS = 'UPDATE_SELECTED_ADDRESS';
export const RESET_CART_SESSION = 'RESET_CART_SESSION';
export const UPDATE_TIP = 'UPDATE_TIP';
export const UPDATE_COUPON = 'UPDATE_COUPON';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';
export const UPDATE_DELIVERY_SHOP_INSTRUCTIONS =
  'UPDATE_DELIVERY_SHOP_INSTRUCTIONS';
export const UPDATE_DELIVERY_INSTRUCTIONS = 'UPDATE_DELIVERY_INSTRUCTIONS';
export const UPDATE_NO_CONTACT_DELIVERY = 'UPDATE_NO_CONTACT_DELIVERY';
export const UPDATE_DELIVERY_TYPE = 'UPDATE_DELIVERY_TYPE';
export const SAVE_DATE = 'SAVE_DATE';
export const SAVE_TIME = 'SAVE_TIME';
export const UPDATE_WALLET = 'UPDATE_WALLET';
export const PREORDERID = 'PREORDERID';
export const PREORDERDATE = 'PREORDERDATE';
export const SHOPID = 'SHOPID';
export const PREORDERSTATUS = 'PREORDERSTATUS';
export const DEVICE = 'DEVICE';
export const AMOUNT = 'AMOUNT';
export const INT_PRODUCT = 'INT_PRODUCT';
// Pick and Drop
export const PICKUP_SERVICE = 'PICKUP_SERVICE';
export const UPDATE_PICKUP_ADDRESS = 'UPDATE_PICKUP_ADDRESS';
export const UPDATE_DROP_ADDRESS = 'UPDATE_DROP_ADDRESS';
export const PICKUP_TEXT = 'PICKUP_TEXT';
export const PICKUP_IMAGE = 'PICKUP_IMAGE';
export const PICKUP_DOCUMENT = 'PICKUP_DOCUMENT';
export const PICKUP_CHARGE = 'PICKUP_CHARGE';
export const PICKUP_TIP = 'PICKUP_TIP';
export const PICKUP_PEAK_CHARGE = 'PICKUP_PEAK_CHARGE';
export const PICKUP_PEAK_COMMENT = 'PICKUP_PEAK_COMMENT';
export const PICKUP_NUMBER = 'PICKUP_NUMBER';
export const DROP_NUMBER = 'DROP_NUMBER';
export const PICKUP_TYPE = 'PICKUP_TYPE';
export const TRIP_TYPE = 'TRIP_TYPE';
export const TASK_CHARGE = 'TASK_CHARGE';
export const PICK_BATCH_ORDER_ADDRESSES = 'BATCH_ORDER_ADDRESSES';
export const TOTAL = 'TOTAL';
export const DELIVERY_CHARGE = 'DELIVERY_CHARGE';
export const SUBSCRIPTION_START_DATE = 'SUBSCRIPTION_START_DATE';
export const CATEGORY_LIST = 'CATEGORY_LIST';
export const CUSTOMIZED_DAY = 'CUSTOMIZED_DAY';
